using Microsoft.EntityFrameworkCore;
using Afra.Domain.Entities;

namespace Afra.Repository.Implimentation
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        {
        }

         public DbSet<WorkFlows> WorkFlowss { get; set; }
  public DbSet<WorkFlowsForm> WorkFlowsForms { get; set; }
  public DbSet<WorkFlowSteps> WorkFlowStepss { get; set; }
  public DbSet<WorkStation> WorkStations { get; set; }
  public DbSet<WebDocs> WebDocss { get; set; }
  public DbSet<WebImages> WebImagess { get; set; }
  public DbSet<WebLogins> WebLoginss { get; set; }
  public DbSet<WebMessages> WebMessagess { get; set; }
  public DbSet<UsrBuyService> UsrBuyServices { get; set; }
  public DbSet<UsrBuyServiceDet> UsrBuyServiceDets { get; set; }
  public DbSet<UsrCash> UsrCashs { get; set; }
  public DbSet<UsrCashDet> UsrCashDets { get; set; }
  public DbSet<UsrContInf> UsrContInfs { get; set; }
  public DbSet<UsrCrsOthInf> UsrCrsOthInfs { get; set; }
  public DbSet<UsrExhibitionRqst> UsrExhibitionRqsts { get; set; }
  public DbSet<UsrMissionDet> UsrMissionDets { get; set; }
  public DbSet<UsrNewsCheckRqst> UsrNewsCheckRqsts { get; set; }
  public DbSet<UsrPersHrmRels> UsrPersHrmRelss { get; set; }
  public DbSet<UsrPersHrmRelsAppl> UsrPersHrmRelsAppls { get; set; }
  public DbSet<UsrPersHrmRelsCons> UsrPersHrmRelsConss { get; set; }
  public DbSet<UsrPersHrmRelsDoc> UsrPersHrmRelsDocs { get; set; }
  public DbSet<UsrPersHrmRelsKigr> UsrPersHrmRelsKigrs { get; set; }
  public DbSet<UsrPersHrmRelsRehab> UsrPersHrmRelsRehabs { get; set; }
  public DbSet<UsrProdCost> UsrProdCosts { get; set; }
  public DbSet<UsrProdExt> UsrProdExts { get; set; }
  public DbSet<UsrProdRcv> UsrProdRcvs { get; set; }
  public DbSet<UsrProdRes> UsrProdRess { get; set; }
  public DbSet<UsrProdVch> UsrProdVchs { get; set; }
  public DbSet<UsrProdWast> UsrProdWasts { get; set; }
  public DbSet<UsrRqstVac> UsrRqstVacs { get; set; }
  public DbSet<UsrTest1> UsrTest1s { get; set; }
  public DbSet<UsrTestForm> UsrTestForms { get; set; }
  public DbSet<UsrTestGrid> UsrTestGrids { get; set; }
  public DbSet<UsrTrsRqstBankInf> UsrTrsRqstBankInfs { get; set; }
  public DbSet<UsrvchBaseInfo> UsrvchBaseInfos { get; set; }
  public DbSet<UserAccess> UserAccesss { get; set; }
  public DbSet<UserAlternative> UserAlternatives { get; set; }
  public DbSet<UserArchive> UserArchives { get; set; }
  public DbSet<UserArchType> UserArchTypes { get; set; }
  public DbSet<UserPlaning> UserPlanings { get; set; }
  public DbSet<UserPlaningDet> UserPlaningDets { get; set; }
  public DbSet<UserPlaningDetInf> UserPlaningDetInfs { get; set; }
  public DbSet<UserProcess> UserProcesss { get; set; }
  public DbSet<UserProcessStp> UserProcessStps { get; set; }
  public DbSet<UserRepAccess> UserRepAccesss { get; set; }
  public DbSet<Users> Userss { get; set; }
  public DbSet<UserSignRight> UserSignRights { get; set; }
  public DbSet<UsersRels> UsersRelss { get; set; }
  public DbSet<UsGroupAccess> UsGroupAccesss { get; set; }
  public DbSet<UsGroupRepAccess> UsGroupRepAccesss { get; set; }
  public DbSet<UsGroups> UsGroupss { get; set; }
  public DbSet<TrsAccOpr> TrsAccOprs { get; set; }
  public DbSet<TrsBankAccounts> TrsBankAccountss { get; set; }
  public DbSet<TrsBankBill> TrsBankBills { get; set; }
  public DbSet<TrsBankBillDet> TrsBankBillDets { get; set; }
  public DbSet<TrsBankBranchs> TrsBankBranchss { get; set; }
  public DbSet<TrsBankChqs> TrsBankChqss { get; set; }
  public DbSet<TrsBankChqsDet> TrsBankChqsDets { get; set; }
  public DbSet<TrsBankReconcile> TrsBankReconciles { get; set; }
  public DbSet<TrsBankReconcileDet> TrsBankReconcileDets { get; set; }
  public DbSet<TrsBanks> TrsBankss { get; set; }
  public DbSet<TrsCalcFormula> TrsCalcFormulas { get; set; }
  public DbSet<TrsCashs> TrsCashss { get; set; }
  public DbSet<TrsChqFmt> TrsChqFmts { get; set; }
  public DbSet<TrsCostFactors> TrsCostFactorss { get; set; }
  public DbSet<TrsCreditTbl> TrsCreditTbls { get; set; }
  public DbSet<TrsCreditTblDet> TrsCreditTblDets { get; set; }
  public DbSet<TrsDeposit> TrsDeposits { get; set; }
  public DbSet<TrsDepositCalc> TrsDepositCalcs { get; set; }
  public DbSet<TrsDepositDet> TrsDepositDets { get; set; }
  public DbSet<TrsFacCrdTbl> TrsFacCrdTbls { get; set; }
  public DbSet<TrsFacCrdTblDet> TrsFacCrdTblDets { get; set; }
  public DbSet<TrsFacilities> TrsFacilitiess { get; set; }
  public DbSet<TrsFacilitiesDet> TrsFacilitiesDets { get; set; }
  public DbSet<TrsFacilitiesGua> TrsFacilitiesGuas { get; set; }
  public DbSet<TrsFacilitiesSec> TrsFacilitiesSecs { get; set; }
  public DbSet<TrsFacManCredit> TrsFacManCredits { get; set; }
  public DbSet<TrsFacTypeInf> TrsFacTypeInfs { get; set; }
  public DbSet<TrsFacYearShare> TrsFacYearShares { get; set; }
  public DbSet<TrsFContract> TrsFContracts { get; set; }
  public DbSet<TrsFContractDet> TrsFContractDets { get; set; }
  public DbSet<TrsFixAcc> TrsFixAccs { get; set; }
  public DbSet<TrsFixAccDet> TrsFixAccDets { get; set; }
  public DbSet<TrsFundBillHdr> TrsFundBillHdrs { get; set; }
  public DbSet<TrsFundBillItm> TrsFundBillItms { get; set; }
  public DbSet<TrsFundItmDet> TrsFundItmDets { get; set; }
  public DbSet<TrsFundOpr> TrsFundOprs { get; set; }
  public DbSet<TrsFunds> TrsFundss { get; set; }
  public DbSet<TrsGContract> TrsGContracts { get; set; }
  public DbSet<TrsGContractChng> TrsGContractChngs { get; set; }
  public DbSet<TrsGuarantee> TrsGuarantees { get; set; }
  public DbSet<TrsGuaranteeGua> TrsGuaranteeGuas { get; set; }
  public DbSet<TrsGuaranteeOpr> TrsGuaranteeOprs { get; set; }
  public DbSet<TrsGuaranteeSec> TrsGuaranteeSecs { get; set; }
  public DbSet<TrsGuaYearShare> TrsGuaYearShares { get; set; }
  public DbSet<TrsManCredit> TrsManCredits { get; set; }
  public DbSet<TrsPayBoredItm> TrsPayBoredItms { get; set; }
  public DbSet<TrsPayBoredOpr> TrsPayBoredOprs { get; set; }
  public DbSet<TrsPayChqItm> TrsPayChqItms { get; set; }
  public DbSet<TrsPayChqOpr> TrsPayChqOprs { get; set; }
  public DbSet<TrsPayHistory> TrsPayHistorys { get; set; }
  public DbSet<TrsRcvBoredItm> TrsRcvBoredItms { get; set; }
  public DbSet<TrsRcvBoredOpr> TrsRcvBoredOprs { get; set; }
  public DbSet<TrsRcvChqItm> TrsRcvChqItms { get; set; }
  public DbSet<TrsRcvChqOpr> TrsRcvChqOprs { get; set; }
  public DbSet<TrsRcvHistory> TrsRcvHistorys { get; set; }
  public DbSet<TrsRqstHdr> TrsRqstHdrs { get; set; }
  public DbSet<TrsRqstItm> TrsRqstItms { get; set; }
  public DbSet<TrsSourceUse> TrsSourceUses { get; set; }
  public DbSet<TrsSourceUseRels> TrsSourceUseRelss { get; set; }
  public DbSet<TrsVchHdr> TrsVchHdrs { get; set; }
  public DbSet<TrsVchItm> TrsVchItms { get; set; }
  public DbSet<TrsVchItmBase> TrsVchItmBases { get; set; }
  public DbSet<TrsVchItmRel> TrsVchItmRels { get; set; }
  public DbSet<TrsVchSrcUse> TrsVchSrcUses { get; set; }
  public DbSet<StkPeriods> StkPeriodss { get; set; }
  public DbSet<StkStockDocs> StkStockDocss { get; set; }
  public DbSet<StkStockerInit> StkStockerInits { get; set; }
  public DbSet<StkStockers> StkStockerss { get; set; }
  public DbSet<StkStockTrans> StkStockTranss { get; set; }
  public DbSet<SMSMethod> SMSMethods { get; set; }
  public DbSet<SMSOperate> SMSOperates { get; set; }
  public DbSet<SMSOperateDet> SMSOperateDets { get; set; }
  public DbSet<SMSSetting> SMSSettings { get; set; }
  public DbSet<ShopGiftCard> ShopGiftCards { get; set; }
  public DbSet<ShopGiftPart> ShopGiftParts { get; set; }
  public DbSet<ShopPartPrice> ShopPartPrices { get; set; }
  public DbSet<Shops> Shopss { get; set; }
  public DbSet<ShopTaxVals> ShopTaxValss { get; set; }
  public DbSet<SleAftSrv> SleAftSrvs { get; set; }
  public DbSet<SleBranchs> SleBranchss { get; set; }
  public DbSet<SleBrokerCalc> SleBrokerCalcs { get; set; }
  public DbSet<SleBrokers> SleBrokerss { get; set; }
  public DbSet<SleBrokerSalary> SleBrokerSalarys { get; set; }
  public DbSet<SleBrokerSalaryMthd> SleBrokerSalaryMthds { get; set; }
  public DbSet<SleBrokerSalaryRels> SleBrokerSalaryRelss { get; set; }
  public DbSet<SleBrokerSalaryTax> SleBrokerSalaryTaxs { get; set; }
  public DbSet<SleChngVchHdr> SleChngVchHdrs { get; set; }
  public DbSet<SleChngVchItm> SleChngVchItms { get; set; }
  public DbSet<SleChngVchTax> SleChngVchTaxs { get; set; }
  public DbSet<SleCstmrBrokers> SleCstmrBrokerss { get; set; }
  public DbSet<SleCstmrGroups> SleCstmrGroupss { get; set; }
  public DbSet<SleCstmrLimit> SleCstmrLimits { get; set; }
  public DbSet<SleCstmrs> SleCstmrss { get; set; }
  public DbSet<SleCtgry> SleCtgrys { get; set; }
  public DbSet<SleCtgryAcc> SleCtgryAccs { get; set; }
  public DbSet<SleDebCreHdr> SleDebCreHdrs { get; set; }
  public DbSet<SleDebCreItm> SleDebCreItms { get; set; }
  public DbSet<SleFixAcc> SleFixAccs { get; set; }
  public DbSet<SleGuaDocs> SleGuaDocss { get; set; }
  public DbSet<SleGuarantee> SleGuarantees { get; set; }
  public DbSet<SleLimits> SleLimitss { get; set; }
  public DbSet<SlePlaces> SlePlacess { get; set; }
  public DbSet<SlePriceHdr> SlePriceHdrs { get; set; }
  public DbSet<SlePriceItm> SlePriceItms { get; set; }
  public DbSet<SleServices> SleServicess { get; set; }
  public DbSet<SleSrvGroups> SleSrvGroupss { get; set; }
  public DbSet<SleSrvHdr> SleSrvHdrs { get; set; }
  public DbSet<SleSrvItm> SleSrvItms { get; set; }
  public DbSet<SleSrvPrcHdr> SleSrvPrcHdrs { get; set; }
  public DbSet<SleSrvPrcItm> SleSrvPrcItms { get; set; }
  public DbSet<SleSrvTax> SleSrvTaxs { get; set; }
  public DbSet<SleTaxDefVal> SleTaxDefVals { get; set; }
  public DbSet<SleTaxes> SleTaxess { get; set; }
  public DbSet<SleTypes> SleTypess { get; set; }
  public DbSet<SleVchHdr> SleVchHdrs { get; set; }
  public DbSet<SleVchItm> SleVchItms { get; set; }
  public DbSet<SleVchQtyVal> SleVchQtyVals { get; set; }
  public DbSet<SleVchTax> SleVchTaxs { get; set; }
  public DbSet<SleVchTypes> SleVchTypess { get; set; }
  public DbSet<QcsBases> QcsBasess { get; set; }
  public DbSet<QcsDocs> QcsDocss { get; set; }
  public DbSet<QcsMenLabs> QcsMenLabss { get; set; }
  public DbSet<QcsMens> QcsMenss { get; set; }
  public DbSet<QcsRequest> QcsRequests { get; set; }
  public DbSet<QcsTestDet> QcsTestDets { get; set; }
  public DbSet<QcsTestDocs> QcsTestDocss { get; set; }
  public DbSet<QcsTests> QcsTestss { get; set; }
  public DbSet<QcsVchHdr> QcsVchHdrs { get; set; }
  public DbSet<QcsVchItm> QcsVchItms { get; set; }
  public DbSet<PrdCalender> PrdCalenders { get; set; }
  public DbSet<PrdConsumHdr> PrdConsumHdrs { get; set; }
  public DbSet<PrdConsumItm> PrdConsumItms { get; set; }
  public DbSet<PrdFixInf> PrdFixInfs { get; set; }
  public DbSet<PrdFixStop> PrdFixStops { get; set; }
  public DbSet<PrdMachine> PrdMachines { get; set; }
  public DbSet<PrdMacro> PrdMacros { get; set; }
  public DbSet<PrdMatPkg> PrdMatPkgs { get; set; }
  public DbSet<PrdMatPlan> PrdMatPlans { get; set; }
  public DbSet<PrdOperation> PrdOperations { get; set; }
  public DbSet<PrdOprDet> PrdOprDets { get; set; }
  public DbSet<PrdOprDetInf> PrdOprDetInfs { get; set; }
  public DbSet<PrdOprDetPers> PrdOprDetPerss { get; set; }
  public DbSet<PrdOrdHdr> PrdOrdHdrs { get; set; }
  public DbSet<PrdOrdItm> PrdOrdItms { get; set; }
  public DbSet<PrdOrdSched> PrdOrdScheds { get; set; }
  public DbSet<PrdPers> PrdPerss { get; set; }
  public DbSet<PrdPersWorkSt> PrdPersWorkSts { get; set; }
  public DbSet<PrdPOrdHdr> PrdPOrdHdrs { get; set; }
  public DbSet<PrdPOrdItm> PrdPOrdItms { get; set; }
  public DbSet<PrdPOrdItmDet> PrdPOrdItmDets { get; set; }
  public DbSet<PrdSchStop> PrdSchStops { get; set; }
  public DbSet<PrdSendHdr> PrdSendHdrs { get; set; }
  public DbSet<PrdSendItm> PrdSendItms { get; set; }
  public DbSet<PrdShifts> PrdShiftss { get; set; }
  public DbSet<PrdStop> PrdStops { get; set; }
  public DbSet<PrdStopItm> PrdStopItms { get; set; }
  public DbSet<PrdVchHdr> PrdVchHdrs { get; set; }
  public DbSet<PrdVchInvDet> PrdVchInvDets { get; set; }
  public DbSet<PrdVchItm> PrdVchItms { get; set; }
  public DbSet<Projects> Projectss { get; set; }
  public DbSet<PayAccVch> PayAccVchs { get; set; }
  public DbSet<PayAccVchDet> PayAccVchDets { get; set; }
  public DbSet<PayBdgBase> PayBdgBases { get; set; }
  public DbSet<PayBdgState> PayBdgStates { get; set; }
  public DbSet<PayBdgVals> PayBdgValss { get; set; }
  public DbSet<PayBuyBase> PayBuyBases { get; set; }
  public DbSet<PayBuyCalc> PayBuyCalcs { get; set; }
  public DbSet<PayCalcBase> PayCalcBases { get; set; }
  public DbSet<PayCalcCtrl> PayCalcCtrls { get; set; }
  public DbSet<PayCalcCtrlDet> PayCalcCtrlDets { get; set; }
  public DbSet<PayCalcState> PayCalcStates { get; set; }
  public DbSet<PayCalcVals> PayCalcValss { get; set; }
  public DbSet<PayCompBranchs> PayCompBranchss { get; set; }
  public DbSet<PayComps> PayCompss { get; set; }
  public DbSet<PayCtrl> PayCtrls { get; set; }
  public DbSet<PayElmntRels> PayElmntRelss { get; set; }
  public DbSet<PayExpDet> PayExpDets { get; set; }
  public DbSet<PayExportFiles> PayExportFiless { get; set; }
  public DbSet<PayFish> PayFishs { get; set; }
  public DbSet<PayFishElmnt> PayFishElmnts { get; set; }
  public DbSet<PayFixElmnt> PayFixElmnts { get; set; }
  public DbSet<PayFixElmntVal> PayFixElmntVals { get; set; }
  public DbSet<PayGrpLoan> PayGrpLoans { get; set; }
  public DbSet<PayGrpLoanPers> PayGrpLoanPerss { get; set; }
  public DbSet<PayGrpValStat> PayGrpValStats { get; set; }
  public DbSet<PayGrpValStatAmnt> PayGrpValStatAmnts { get; set; }
  public DbSet<PayGrpValStatPers> PayGrpValStatPerss { get; set; }
  public DbSet<PayImpDet> PayImpDets { get; set; }
  public DbSet<PayImportFiles> PayImportFiless { get; set; }
  public DbSet<PayLoanHistory> PayLoanHistorys { get; set; }
  public DbSet<PayLoanPayment> PayLoanPayments { get; set; }
  public DbSet<PayLoanRcv> PayLoanRcvs { get; set; }
  public DbSet<PayLoanTypes> PayLoanTypess { get; set; }
  public DbSet<PayMonthlyMthd> PayMonthlyMthds { get; set; }
  public DbSet<PayMonthlyVals> PayMonthlyValss { get; set; }
  public DbSet<PayPersEnd> PayPersEnds { get; set; }
  public DbSet<PayRepLists> PayRepListss { get; set; }
  public DbSet<PaySystems> PaySystemss { get; set; }
  public DbSet<PayTaxComps> PayTaxCompss { get; set; }
  public DbSet<PayTaxDet> PayTaxDets { get; set; }
  public DbSet<PayTaxTable> PayTaxTables { get; set; }
  public DbSet<PayUserField> PayUserFields { get; set; }
  public DbSet<PayUserFuns> PayUserFunss { get; set; }
  public DbSet<PayVacMonthly> PayVacMonthlys { get; set; }
  public DbSet<PayVacRemain> PayVacRemains { get; set; }
  public DbSet<PayValStatAmnt> PayValStatAmnts { get; set; }
  public DbSet<PayValStats> PayValStatss { get; set; }
  public DbSet<PayVchDet> PayVchDets { get; set; }
  public DbSet<PayVchDetInfs> PayVchDetInfss { get; set; }
  public DbSet<PayVchType> PayVchTypes { get; set; }
  public DbSet<PayWorkLimit> PayWorkLimits { get; set; }
  public DbSet<PartFormula> PartFormulas { get; set; }
  public DbSet<PartFormulaDet> PartFormulaDets { get; set; }
  public DbSet<PartFrmlMach> PartFrmlMachs { get; set; }
  public DbSet<PartFrmlOut> PartFrmlOuts { get; set; }
  public DbSet<Parts> Partss { get; set; }
  public DbSet<PmiReqPart> PmiReqParts { get; set; }
  public DbSet<OtoAttach> OtoAttachs { get; set; }
  public DbSet<OtoBaseTypes> OtoBaseTypess { get; set; }
  public DbSet<OtoBaseTypeVals> OtoBaseTypeValss { get; set; }
  public DbSet<OtoCtgry> OtoCtgrys { get; set; }
  public DbSet<OtoFiles> OtoFiless { get; set; }
  public DbSet<OtoFlow> OtoFlows { get; set; }
  public DbSet<OtoFlowCrs> OtoFlowCrss { get; set; }
  public DbSet<OtoFlowRight> OtoFlowRights { get; set; }
  public DbSet<OtoIndicator> OtoIndicators { get; set; }
  public DbSet<OtoLetters> OtoLetterss { get; set; }
  public DbSet<OtoLttrDoc> OtoLttrDocs { get; set; }
  public DbSet<OtoLttrLabels> OtoLttrLabelss { get; set; }
  public DbSet<OtoLttrLinks> OtoLttrLinkss { get; set; }
  public DbSet<OtoLttrProps> OtoLttrPropss { get; set; }
  public DbSet<OtoQuickNote> OtoQuickNotes { get; set; }
  public DbSet<OtoSysLttr> OtoSysLttrs { get; set; }
  public DbSet<OtoTemplates> OtoTemplatess { get; set; }
  public DbSet<OtoTransScript> OtoTransScripts { get; set; }
  public DbSet<OtoUserRight> OtoUserRights { get; set; }
  public DbSet<InvFormHdr> InvFormHdrs { get; set; }
  public DbSet<InvFormItm> InvFormItms { get; set; }
  public DbSet<InvFormTypes> InvFormTypess { get; set; }
  public DbSet<InvItmRateDet> InvItmRateDets { get; set; }
  public DbSet<InvPartCmrInf> InvPartCmrInfs { get; set; }
  public DbSet<InvPartCtgry> InvPartCtgrys { get; set; }
  public DbSet<InvPartCtgryAcc> InvPartCtgryAccs { get; set; }
  public DbSet<InvPartDLInf> InvPartDLInfs { get; set; }
  public DbSet<InvPartGroups> InvPartGroupss { get; set; }
  public DbSet<InvPartGrpRel> InvPartGrpRels { get; set; }
  public DbSet<InvPartParams> InvPartParamss { get; set; }
  public DbSet<InvPartPrice> InvPartPrices { get; set; }
  public DbSet<InvPartSimilar> InvPartSimilars { get; set; }
  public DbSet<InvPartStkPitchRel> InvPartStkPitchRels { get; set; }
  public DbSet<InvPartStockRel> InvPartStockRels { get; set; }
  public DbSet<InvPartUnits> InvPartUnitss { get; set; }
  public DbSet<InvQtPartRels> InvQtPartRelss { get; set; }
  public DbSet<InvQtyCtrls> InvQtyCtrlss { get; set; }
  public DbSet<InvStckPeriod> InvStckPeriods { get; set; }
  public DbSet<InvStckPeriodRels> InvStckPeriodRelss { get; set; }
  public DbSet<InvStckTag> InvStckTags { get; set; }
  public DbSet<InvStkPitchs> InvStkPitchss { get; set; }
  public DbSet<InvStock> InvStocks { get; set; }
  public DbSet<InvStockUser> InvStockUsers { get; set; }
  public DbSet<InvVchDefAcc> InvVchDefAccs { get; set; }
  public DbSet<InvVchHdr> InvVchHdrs { get; set; }
  public DbSet<InvVchItm> InvVchItms { get; set; }
  public DbSet<InvVchItmRate> InvVchItmRates { get; set; }
  public DbSet<InvVchQtyVal> InvVchQtyVals { get; set; }
  public DbSet<InvVchTrans> InvVchTranss { get; set; }
  public DbSet<InvVchTypes> InvVchTypess { get; set; }
  public DbSet<HrmAimElmnts> HrmAimElmntss { get; set; }
  public DbSet<HrmAimFormDet> HrmAimFormDets { get; set; }
  public DbSet<HrmAimForms> HrmAimFormss { get; set; }
  public DbSet<HrmAimPeriod> HrmAimPeriods { get; set; }
  public DbSet<HrmAimPeriodDet> HrmAimPeriodDets { get; set; }
  public DbSet<HrmBaseAmounts> HrmBaseAmountss { get; set; }
  public DbSet<HrmBases> HrmBasess { get; set; }
  public DbSet<HrmCalendars> HrmCalendarss { get; set; }
  public DbSet<HrmCalenderDet> HrmCalenderDets { get; set; }
  public DbSet<HrmDept> HrmDepts { get; set; }
  public DbSet<HrmDeptJobRel> HrmDeptJobRels { get; set; }
  public DbSet<HrmEmpStatAmnt> HrmEmpStatAmnts { get; set; }
  public DbSet<HrmEmpStatue> HrmEmpStatues { get; set; }
  public DbSet<HrmEmpTypes> HrmEmpTypess { get; set; }
  public DbSet<HrmGroups> HrmGroupss { get; set; }
  public DbSet<HrmGrpCompAsign> HrmGrpCompAsigns { get; set; }
  public DbSet<HrmGrpParamStat> HrmGrpParamStats { get; set; }
  public DbSet<HrmGrpParamStatAmnt> HrmGrpParamStatAmnts { get; set; }
  public DbSet<HrmGrpParamStatPers> HrmGrpParamStatPerss { get; set; }
  public DbSet<HrmGrpStatAmnts> HrmGrpStatAmntss { get; set; }
  public DbSet<HrmGrpStatPers> HrmGrpStatPerss { get; set; }
  public DbSet<HrmGrpStatus> HrmGrpStatuss { get; set; }
  public DbSet<HrmIncDecVac> HrmIncDecVacs { get; set; }
  public DbSet<HrmIncDecWork> HrmIncDecWorks { get; set; }
  public DbSet<HrmJobCond> HrmJobConds { get; set; }
  public DbSet<HrmJobs> HrmJobss { get; set; }
  public DbSet<HrmMissions> HrmMissionss { get; set; }
  public DbSet<HrmNumbering> HrmNumberings { get; set; }
  public DbSet<HrmOvrTimePerm> HrmOvrTimePerms { get; set; }
  public DbSet<HrmParamStatAmnt> HrmParamStatAmnts { get; set; }
  public DbSet<HrmParamStats> HrmParamStatss { get; set; }
  public DbSet<HrmPersAccount> HrmPersAccounts { get; set; }
  public DbSet<HrmPersCompAsign> HrmPersCompAsigns { get; set; }
  public DbSet<HrmPersEdu> HrmPersEdus { get; set; }
  public DbSet<HrmPersExp> HrmPersExps { get; set; }
  public DbSet<HrmPersFgh> HrmPersFghs { get; set; }
  public DbSet<HrmPersLang> HrmPersLangs { get; set; }
  public DbSet<HrmPersMrg> HrmPersMrgs { get; set; }
  public DbSet<HrmPersonnels> HrmPersonnelss { get; set; }
  public DbSet<HrmPersParam> HrmPersParams { get; set; }
  public DbSet<HrmPersRltd> HrmPersRltds { get; set; }
  public DbSet<HrmPersSldr> HrmPersSldrs { get; set; }
  public DbSet<HrmPrsntStat> HrmPrsntStats { get; set; }
  public DbSet<HrmRqstMission> HrmRqstMissions { get; set; }
  public DbSet<HrmRqstVac> HrmRqstVacs { get; set; }
  public DbSet<HrmStatElmntMthd> HrmStatElmntMthds { get; set; }
  public DbSet<HrmStatMthdDet> HrmStatMthdDets { get; set; }
  public DbSet<HrmStatTypes> HrmStatTypess { get; set; }
  public DbSet<HrmTables> HrmTabless { get; set; }
  public DbSet<HrmTablesDet> HrmTablesDets { get; set; }
  public DbSet<HrmTimeSheet> HrmTimeSheets { get; set; }
  public DbSet<HrmVacancy> HrmVacancys { get; set; }
  public DbSet<HrmVacMthods> HrmVacMthodss { get; set; }
  public DbSet<HrmWorkGroups> HrmWorkGroupss { get; set; }
  public DbSet<HrmWorkGroupsInf> HrmWorkGroupsInfs { get; set; }
  public DbSet<HrmWorkLoc> HrmWorkLocs { get; set; }
  public DbSet<GnrAlarmDet> GnrAlarmDets { get; set; }
  public DbSet<GnrAlarmTypes> GnrAlarmTypess { get; set; }
  public DbSet<GnrAutoText> GnrAutoTexts { get; set; }
  public DbSet<GnrDashboards> GnrDashboardss { get; set; }
  public DbSet<GnrDashFields> GnrDashFieldss { get; set; }
  public DbSet<GnrFormFlow> GnrFormFlows { get; set; }
  public DbSet<GnrFormRepRels> GnrFormRepRelss { get; set; }
  public DbSet<GnrFormSetting> GnrFormSettings { get; set; }
  public DbSet<GnrLimitExcept> GnrLimitExcepts { get; set; }
  public DbSet<GnrLimitGroup> GnrLimitGroups { get; set; }
  public DbSet<GnrLimitUser> GnrLimitUsers { get; set; }
  public DbSet<GnrNumVchCfgDet> GnrNumVchCfgDets { get; set; }
  public DbSet<GnrNumVchConfig> GnrNumVchConfigs { get; set; }
  public DbSet<GnrProcess> GnrProcesss { get; set; }
  public DbSet<GnrProcessDet> GnrProcessDets { get; set; }
  public DbSet<GnrProcessDetArch> GnrProcessDetArchs { get; set; }
  public DbSet<GnrProcessDetObj> GnrProcessDetObjs { get; set; }
  public DbSet<GnrProcessDetTrans> GnrProcessDetTranss { get; set; }
  public DbSet<GnrProcessDetUsers> GnrProcessDetUserss { get; set; }
  public DbSet<GnrProcessDetVals> GnrProcessDetValss { get; set; }
  public DbSet<GnrRef2FormLinkExp> GnrRef2FormLinkExps { get; set; }
  public DbSet<GnrRef2FormLinkHdr> GnrRef2FormLinkHdrs { get; set; }
  public DbSet<GnrRef2FormLinksItm> GnrRef2FormLinksItms { get; set; }
  public DbSet<GnrRefFormsList> GnrRefFormsLists { get; set; }
  public DbSet<GnrRefFormsListDet> GnrRefFormsListDets { get; set; }
  public DbSet<GnrReports> GnrReportss { get; set; }
  public DbSet<GnrRptGroups> GnrRptGroupss { get; set; }
  public DbSet<GnrSysFormObjects> GnrSysFormObjectss { get; set; }
  public DbSet<GnrSysForms> GnrSysFormss { get; set; }
  public DbSet<GnrSysLogs> GnrSysLogss { get; set; }
  public DbSet<GnrSysMsg> GnrSysMsgs { get; set; }
  public DbSet<GnrSysMsgDet> GnrSysMsgDets { get; set; }
  public DbSet<GnrSysQryFields> GnrSysQryFieldss { get; set; }
  public DbSet<GnrSysQuerys> GnrSysQueryss { get; set; }
  public DbSet<GnrSysTables> GnrSysTabless { get; set; }
  public DbSet<GnrTableRelation> GnrTableRelations { get; set; }
  public DbSet<GnrTablesDet> GnrTablesDets { get; set; }
  public DbSet<GnrTablesInf> GnrTablesInfs { get; set; }
  public DbSet<GnrTools> GnrToolss { get; set; }
  public DbSet<GnrUFCtgry> GnrUFCtgrys { get; set; }
  public DbSet<GnrUserAlarms> GnrUserAlarmss { get; set; }
  public DbSet<GnrUserField> GnrUserFields { get; set; }
  public DbSet<GnrUserFormDesign> GnrUserFormDesigns { get; set; }
  public DbSet<GnrUserFormOprs> GnrUserFormOprss { get; set; }
  public DbSet<GnrUserForms> GnrUserFormss { get; set; }
  public DbSet<GnrUserLabels> GnrUserLabelss { get; set; }
  public DbSet<GnrUserLog> GnrUserLogs { get; set; }
  public DbSet<GnrUserMsg> GnrUserMsgs { get; set; }
  public DbSet<GnrUserRefList> GnrUserRefLists { get; set; }
  public DbSet<GnrUserRefListDet> GnrUserRefListDets { get; set; }
  public DbSet<GnrUserRole> GnrUserRoles { get; set; }
  public DbSet<GnrUserStorage> GnrUserStorages { get; set; }
  public DbSet<GnrValidData> GnrValidDatas { get; set; }
  public DbSet<GeoPos> GeoPoss { get; set; }
  public DbSet<Address> Addresss { get; set; }
  public DbSet<Crspnds> Crspndss { get; set; }
  public DbSet<Lookups> Lookupss { get; set; }
  public DbSet<Settings> Settingss { get; set; }
  public DbSet<sysdiagrams> sysdiagramss { get; set; }
  public DbSet<TablesLastId> TablesLastIds { get; set; }
  public DbSet<TaxDutyInf> TaxDutyInfs { get; set; }
  public DbSet<Units> Unitss { get; set; }
  public DbSet<ElementRoles> ElementRoless { get; set; }
  public DbSet<Elements> Elementss { get; set; }
  public DbSet<ElmntMethod> ElmntMethods { get; set; }
  public DbSet<ElmntMethodRoles> ElmntMethodRoless { get; set; }
  public DbSet<CurExChange> CurExChanges { get; set; }
  public DbSet<Currency> Currencys { get; set; }
  public DbSet<CostCenters> CostCenterss { get; set; }
  public DbSet<CstAccData> CstAccDatas { get; set; }
  public DbSet<CstAccRelInf> CstAccRelInfs { get; set; }
  public DbSet<CstCostAllocDet> CstCostAllocDets { get; set; }
  public DbSet<CstCostCntrAlloc> CstCostCntrAllocs { get; set; }
  public DbSet<CstCostCntrAllocSVals> CstCostCntrAllocSValss { get; set; }
  public DbSet<CstCostCntrAllocVals> CstCostCntrAllocValss { get; set; }
  public DbSet<CstCostCntrElmntRole> CstCostCntrElmntRoles { get; set; }
  public DbSet<CstCostCntrElmntVals> CstCostCntrElmntValss { get; set; }
  public DbSet<CstCostCntrFill> CstCostCntrFills { get; set; }
  public DbSet<CstCostCntrRoleVals> CstCostCntrRoleValss { get; set; }
  public DbSet<CstElements> CstElementss { get; set; }
  public DbSet<CstElmntRoles> CstElmntRoless { get; set; }
  public DbSet<CstMatDurQty> CstMatDurQtys { get; set; }
  public DbSet<CstMatQty> CstMatQtys { get; set; }
  public DbSet<CstMatStdInf> CstMatStdInfs { get; set; }
  public DbSet<CstMatWast> CstMatWasts { get; set; }
  public DbSet<CstPeriods> CstPeriodss { get; set; }
  public DbSet<CstProdDurQty> CstProdDurQtys { get; set; }
  public DbSet<CstProduceInf> CstProduceInfs { get; set; }
  public DbSet<CstProductPackage> CstProductPackages { get; set; }
  public DbSet<CstProductPackDet> CstProductPackDets { get; set; }
  public DbSet<CstProductVch> CstProductVchs { get; set; }
  public DbSet<CstRealCalc> CstRealCalcs { get; set; }
  public DbSet<CstStdAccData> CstStdAccDatas { get; set; }
  public DbSet<CstStdCalc> CstStdCalcs { get; set; }
  public DbSet<CntAccRels> CntAccRelss { get; set; }
  public DbSet<CntAccVchTypes> CntAccVchTypess { get; set; }
  public DbSet<CntAcquitInfs> CntAcquitInfss { get; set; }
  public DbSet<CntAgreement> CntAgreements { get; set; }
  public DbSet<CntAmntCurInf> CntAmntCurInfs { get; set; }
  public DbSet<CntAmntTypes> CntAmntTypess { get; set; }
  public DbSet<CntCMthdFlds> CntCMthdFldss { get; set; }
  public DbSet<CntContAgrVals> CntContAgrValss { get; set; }
  public DbSet<CntContAmntChng> CntContAmntChngs { get; set; }
  public DbSet<CntContDet> CntContDets { get; set; }
  public DbSet<CntContElmnt> CntContElmnts { get; set; }
  public DbSet<CntContractors> CntContractorss { get; set; }
  public DbSet<CntContracts> CntContractss { get; set; }
  public DbSet<CntContRatio> CntContRatios { get; set; }
  public DbSet<CntContrLimit> CntContrLimits { get; set; }
  public DbSet<CntContText> CntContTexts { get; set; }
  public DbSet<CntCrsDocument> CntCrsDocuments { get; set; }
  public DbSet<CntDeliveryInf> CntDeliveryInfs { get; set; }
  public DbSet<CntExpAccntRels> CntExpAccntRelss { get; set; }
  public DbSet<CntExpAcntCostCntr> CntExpAcntCostCntrs { get; set; }
  public DbSet<CntExpAcntData> CntExpAcntDatas { get; set; }
  public DbSet<CntExpAcntDet> CntExpAcntDets { get; set; }
  public DbSet<CntExpAcntFlds> CntExpAcntFldss { get; set; }
  public DbSet<CntExpAcntVals> CntExpAcntValss { get; set; }
  public DbSet<CntExpFldElmnts> CntExpFldElmntss { get; set; }
  public DbSet<CntExpnsAccnts> CntExpnsAccntss { get; set; }
  public DbSet<CntExtendInf> CntExtendInfs { get; set; }
  public DbSet<CntFormFields> CntFormFieldss { get; set; }
  public DbSet<CntFormVals> CntFormValss { get; set; }
  public DbSet<CntGaurantInf> CntGaurantInfs { get; set; }
  public DbSet<CntGnrText> CntGnrTexts { get; set; }
  public DbSet<CntInvoiceDet> CntInvoiceDets { get; set; }
  public DbSet<CntInvoiceHdr> CntInvoiceHdrs { get; set; }
  public DbSet<CntInvoiceNotes> CntInvoiceNotess { get; set; }
  public DbSet<CntInvoiceRels> CntInvoiceRelss { get; set; }
  public DbSet<CntMasterFactData> CntMasterFactDatas { get; set; }
  public DbSet<CntMasterFactor> CntMasterFactors { get; set; }
  public DbSet<CntMasterFactVal> CntMasterFactVals { get; set; }
  public DbSet<CntMasters> CntMasterss { get; set; }
  public DbSet<CntSrvItems> CntSrvItemss { get; set; }
  public DbSet<CntSrvPrcHdr> CntSrvPrcHdrs { get; set; }
  public DbSet<CntSrvPrcItm> CntSrvPrcItms { get; set; }
  public DbSet<CmrContHdr> CmrContHdrs { get; set; }
  public DbSet<CmrContItm> CmrContItms { get; set; }
  public DbSet<CmrFactHdr> CmrFactHdrs { get; set; }
  public DbSet<CmrFactItm> CmrFactItms { get; set; }
  public DbSet<CmrInsurance> CmrInsurances { get; set; }
  public DbSet<CmrInvoiceCost> CmrInvoiceCosts { get; set; }
  public DbSet<CmrInvoiceHdr> CmrInvoiceHdrs { get; set; }
  public DbSet<CmrInvoiceItm> CmrInvoiceItms { get; set; }
  public DbSet<CmrLC> CmrLCs { get; set; }
  public DbSet<CmrLCDet> CmrLCDets { get; set; }
  public DbSet<CmrOrdHdr> CmrOrdHdrs { get; set; }
  public DbSet<CmrOrdItm> CmrOrdItms { get; set; }
  public DbSet<CmrOrdSeller> CmrOrdSellers { get; set; }
  public DbSet<CmrPers> CmrPerss { get; set; }
  public DbSet<CmrPOrderHdr> CmrPOrderHdrs { get; set; }
  public DbSet<CmrPOrderItm> CmrPOrderItms { get; set; }
  public DbSet<CmrPreFactHdr> CmrPreFactHdrs { get; set; }
  public DbSet<CmrPreFactItm> CmrPreFactItms { get; set; }
  public DbSet<CmrRegister> CmrRegisters { get; set; }
  public DbSet<CmrReleaseCost> CmrReleaseCosts { get; set; }
  public DbSet<CmrReleaseHdr> CmrReleaseHdrs { get; set; }
  public DbSet<CmrReleaseItm> CmrReleaseItms { get; set; }
  public DbSet<CmrReleaseStock> CmrReleaseStocks { get; set; }
  public DbSet<CmrRqstHdr> CmrRqstHdrs { get; set; }
  public DbSet<CmrRqstItm> CmrRqstItms { get; set; }
  public DbSet<CmrSellerGrp> CmrSellerGrps { get; set; }
  public DbSet<CmrSellers> CmrSellerss { get; set; }
  public DbSet<CmrSendHdr> CmrSendHdrs { get; set; }
  public DbSet<CmrSendItm> CmrSendItms { get; set; }
  public DbSet<CmrServices> CmrServicess { get; set; }
  public DbSet<CmrTransport> CmrTransports { get; set; }
  public DbSet<CmrTransportDet> CmrTransportDets { get; set; }
  public DbSet<BdgAssets> BdgAssetss { get; set; }
  public DbSet<BdgAssetsDet> BdgAssetsDets { get; set; }
  public DbSet<BdgBalanceVal> BdgBalanceVals { get; set; }
  public DbSet<BdgBalanceValsDet> BdgBalanceValsDets { get; set; }
  public DbSet<BdgContAcc> BdgContAccs { get; set; }
  public DbSet<BdgContAccDet> BdgContAccDets { get; set; }
  public DbSet<BdgConts> BdgContss { get; set; }
  public DbSet<BdgCostAllocDet> BdgCostAllocDets { get; set; }
  public DbSet<BdgCostCntrAlloc> BdgCostCntrAllocs { get; set; }
  public DbSet<BdgCostCntrRoleVals> BdgCostCntrRoleValss { get; set; }
  public DbSet<BdgCurExchange> BdgCurExchanges { get; set; }
  public DbSet<BdgElements> BdgElementss { get; set; }
  public DbSet<BdgElmntRoles> BdgElmntRoless { get; set; }
  public DbSet<BdgElmntVal> BdgElmntVals { get; set; }
  public DbSet<BdgElmntValsDet> BdgElmntValsDets { get; set; }
  public DbSet<BdgFinalRep> BdgFinalReps { get; set; }
  public DbSet<BdgHrmBase> BdgHrmBases { get; set; }
  public DbSet<BdgHrmVals> BdgHrmValss { get; set; }
  public DbSet<BdgHrmValsDet> BdgHrmValsDets { get; set; }
  public DbSet<BdgHrmValsPers> BdgHrmValsPerss { get; set; }
  public DbSet<BdgLevelDet> BdgLevelDets { get; set; }
  public DbSet<BdgParts> BdgPartss { get; set; }
  public DbSet<BdgPartsDet> BdgPartsDets { get; set; }
  public DbSet<BdgPeriods> BdgPeriodss { get; set; }
  public DbSet<BdgProfitDet> BdgProfitDets { get; set; }
  public DbSet<BdgProjDetInf> BdgProjDetInfs { get; set; }
  public DbSet<BdgProjectDet> BdgProjectDets { get; set; }
  public DbSet<BdgProjectHrm> BdgProjectHrms { get; set; }
  public DbSet<BdgProjects> BdgProjectss { get; set; }
  public DbSet<BdgProjElmnt> BdgProjElmnts { get; set; }
  public DbSet<BdgProjElmntVals> BdgProjElmntValss { get; set; }
  public DbSet<BdgProjGroup> BdgProjGroups { get; set; }
  public DbSet<BdgShareRep> BdgShareReps { get; set; }
  public DbSet<BdgTaxDet> BdgTaxDets { get; set; }
  public DbSet<BdgTaxes> BdgTaxess { get; set; }
  public DbSet<BdgTaxPrc> BdgTaxPrcs { get; set; }
  public DbSet<BdgTaxPrcCost> BdgTaxPrcCosts { get; set; }
  public DbSet<BdgTopics> BdgTopicss { get; set; }
  public DbSet<BdgTopicsRels> BdgTopicsRelss { get; set; }
  public DbSet<Assets> Assetss { get; set; }
  public DbSet<AstAssetCost> AstAssetCosts { get; set; }
  public DbSet<AstAssetCtgry> AstAssetCtgrys { get; set; }
  public DbSet<AstAssetDepr> AstAssetDeprs { get; set; }
  public DbSet<AstAssetGrp> AstAssetGrps { get; set; }
  public DbSet<AstAssetInf> AstAssetInfs { get; set; }
  public DbSet<AstAssetRate> AstAssetRates { get; set; }
  public DbSet<AstAssetSale> AstAssetSales { get; set; }
  public DbSet<AstCostDet> AstCostDets { get; set; }
  public DbSet<AstCostDocs> AstCostDocss { get; set; }
  public DbSet<AstDeprVch> AstDeprVchs { get; set; }
  public DbSet<AstDocs> AstDocss { get; set; }
  public DbSet<AstMens> AstMenss { get; set; }
  public DbSet<AstPitchs> AstPitchss { get; set; }
  public DbSet<AstRatioDocs> AstRatioDocss { get; set; }
  public DbSet<AstTransDocs> AstTransDocss { get; set; }
  public DbSet<ArchGroups> ArchGroupss { get; set; }
  public DbSet<Archive> Archives { get; set; }
  public DbSet<ArchTypes> ArchTypess { get; set; }
  public DbSet<AccAnalyse> AccAnalyses { get; set; }
  public DbSet<AccCloseHdr> AccCloseHdrs { get; set; }
  public DbSet<AccCloseItm> AccCloseItms { get; set; }
  public DbSet<AccDL> AccDLs { get; set; }
  public DbSet<AccDLCtgry> AccDLCtgrys { get; set; }
  public DbSet<AccDLCtgryRel> AccDLCtgryRels { get; set; }
  public DbSet<AccGL> AccGLs { get; set; }
  public DbSet<AccGLVchHdr> AccGLVchHdrs { get; set; }
  public DbSet<AccGLVchItm> AccGLVchItms { get; set; }
  public DbSet<AccGroups> AccGroupss { get; set; }
  public DbSet<AccNoteHdr> AccNoteHdrs { get; set; }
  public DbSet<AccNoteItm> AccNoteItms { get; set; }
  public DbSet<AccPeriod> AccPeriods { get; set; }
  public DbSet<AccPL> AccPLs { get; set; }
  public DbSet<AccSL> AccSLs { get; set; }
  public DbSet<AccSLDLRel> AccSLDLRels { get; set; }
  public DbSet<AccSLStdDesc> AccSLStdDescs { get; set; }
  public DbSet<AccTransVch> AccTransVchs { get; set; }
  public DbSet<AccVchDescr> AccVchDescrs { get; set; }
  public DbSet<AccVchHdr> AccVchHdrs { get; set; }
  public DbSet<AccVchItm> AccVchItms { get; set; }
  public DbSet<AccVchKindDescr> AccVchKindDescrs { get; set; }
  public DbSet<AccVchRels> AccVchRelss { get; set; }
  public DbSet<AccVchTypes> AccVchTypess { get; set; }
 

        protected override void OnModelCreating(ModelBuilder builder)
        {
            
        }
    }
}
